

dictionaries:
  daijisen: 
    dict_name: "大辞泉 第二版"
    rev_name: "daijisen2"
    dict_type: "Daijisen"
    parser_module: "parsers.DAIJISEN"
    parser_class_name: "DaijisenParser"
    link_strategy_module: "strategies.plugins.DAIJISEN"
    image_strategy_module: "strategies.plugins.DAIJISEN"
    link_strategy_class: "DaijisenLinkHandlingStrategy"
    image_strategy_class: "DaijisenImageHandlingStrategy"
    tag_map_path: "resources/DAIJISEN/mapping/tag_map.json"
    expression_element: "subitem"
    ignored_elements: {"k-v", "header", "index"}
    normalization_tag_name: "headword"
    normalization_class_name: "見出"
  
  kogo: 
    dict_name: "旺文社全訳古語辞典"
    rev_name: "oubunsha_kogo5"
    dict_type: "OZK5"
    parser_module: "parsers.OZK5"
    parser_class_name: "OZK5Parser"
    link_strategy_module: "parsers.OZK5.ozk5_strategies"
    link_strategy_class: "OZK5LinkHandlingStrategy"
    tag_map_path: "src/parsers/OZK5/tag_map.json"
    has_audio: True
  
  skogo: 
    dict_name: "三省堂全訳読解古語辞典"
    rev_name: "skogo5"
    dict_type: "SKOGO"
    parser_module: "parsers.SKOGO"
    parser_class_name: "SKOGOParser"
    link_strategy_module: "strategies.plugins.SKOGO"
    link_strategy_class: "SKOGOLinkHandlingStrategy"
    normalization_strategy_module: "strategies.plugins.SKOGO"
    normalization_strategy_class: "SKOGONormalizationStrategy"
    image_strategy_module: "strategies.image"
    image_strategy_class: "HashedImageStrategy"
    tag_map_path: "resources/SKOGO/mapping/tag_map.json"
    image_map_path: "resources/SKOGO/mapping/image_map.json"
    normalization_tag_name: "見出G"
    ignored_elements: {"entry-index"}
  
  ydp: 
    dict_name: "有斐閣現代心理学辞典"
    rev_name: "ydp1"
    dict_type: "YDP"
    parser_module: "parsers.Monokakido.parser"
    parser_class_name: "MonokakidoParser"
    image_strategy_module: "strategies.plugins.YDP"
    image_strategy_class: "YDPImageHandlingStrategy"
    tag_map_path: "resources/YDP/mapping/tag_map.json"
    ignored_elements: {"entry-index", "key"}
    normalization_tag_name: "headword"
    normalization_class_name: "見出"

  shinjigen: 
    dict_name: "角川新字源 改訂新版"
    rev_name: "shinjigen2"
    dict_type: "SHINJIGEN2"
    parser_module: "parsers.SHINJIGEN2"
    parser_class_name: "ShinjigenParser"
    image_strategy_module: "strategies.plugins.SHINJIGEN2"
    image_strategy_class: "ShinjigenImageHandlingStrategy"
    tag_map_path: "resources/SHINJIGEN2/mapping/tag_map.json"
    use_index: False
    use_jmdict: False
    ignored_elements: {"entry-index", "link"}
  
  nanmed: 
    dict_name: "南山堂医学大辞典 第20版"
    rev_name: "nanmed20"
    dict_type: "NANMED20"
    parser_module: "parsers.NANMED20"
    parser_class_name: "NanmedParser"
    image_strategy_module: "strategies.plugins.NANMED20"
    image_strategy_class: "NanmedImageHandlingStrategy"
    tag_map_path: "src/parsers/NANMED20/tag_map.json"
    use_index: False
    use_jmdict: False
  
  meikyo: 
    dict_name: "明鏡国語辞典 第三版"
    rev_name: "meikyo3"
    dict_type: "MK3"
    parser_module: "parsers.MK3"
    parser_class_name: "MeikyoParser"
    link_strategy_module: "strategies.plugins.MK3"
    link_strategy_class: "MeikyoLinkHandlingStrategy"
    tag_map_path: "resources/MK3/mapping/tag_map.json"
    ignored_elements: {"link", "meta", "entry-index", "index", "key"}
    expression_element: "child-item"
    normalization_tag_name: "headword"
    normalization_class_name: "見出"
  
  ydl: 
    dict_name: "有斐閣法律用語辞典 第5版"
    rev_name: "ydl"
    dict_type: "YDL"
    parser_module: "parsers.Monokakido.parser"
    parser_class_name: "MonokakidoParser"
    image_strategy_module: "strategies.plugins.YDL"
    image_strategy_class: "YDLImageHandlingStrategy"
    tag_map_path: "resources/YDL/mapping/tag_map.json"
    ignored_elements: {"index", "参照先ID", "管理データ", "項目読み"}
    normalization_tag_name: "項目表示"
  
  tismkanji: 
    dict_name: "TISMKANJI"
    rev_name: "kanjirin"
    dict_type: "TISMKANJI"
    parser_module: "parsers.TISMKANJI"
    parser_class_name: "TismKanjiParser"
    use_index: False
    use_jmdict: False
  
  oko12: 
    dict_name: "旺文社国語辞典 第十二版"
    rev_name: "oko12"
    dict_type: "OKO12"
    parser_module: "parsers.Monokakido.parser"
    parser_class_name: "MonokakidoParser"
    link_strategy_module: "strategies.plugins.OKO12"
    image_strategy_module: "strategies.plugins.OKO12"
    link_strategy_class: "OKO12LinkHandlingStrategy"
    image_strategy_class: "OKO12ImageHandlingStrategy"
    tag_map_path: "resources/OKO12/mapping/tag_map.json"
    ignored_elements: {"entry-index"}
    normalization_tag_name: "headword"
    subitems_not_split: True
  
  rgko12: 
    dict_name: "小学館例解学習国語 第十二版"
    rev_name: "rgko12"
    dict_type: "RGKO12"
    parser_module: "parsers.RGKO12.rgko12_parser"
    parser_class_name: "RGKO12Parser"
    link_strategy_module: "strategies.plugins.RGKO12"
    image_strategy_module: "strategies.plugins.RGKO12"
    link_strategy_class: "RGKO12LinkHandlingStrategy"
    image_strategy_class: "RGKO12ImageHandlingStrategy"
    tag_map_path: "resources/RGKO12/mapping/tag_map.json"
    image_map_path: "resources/RGKO12/mapping/image_map.json"
    appendix_entries_path: "resources/RGKO12/mapping/appendix_entries.json"
    has_appendix: True
    ignored_elements: {"entry-index", "hidden", "ht"}
    normalization_tag_name: "headword"
  
  cj3: 
    dict_name: "小学館中日辞典 第3版"
    rev_name: "cj3"
    dict_type: "CJ3"
    parser_module: "parsers.CJ3.cj3_parser"
    parser_class_name: "CJ3Parser"
    link_strategy_module: "parsers.CJ3.cj3_strategies"
    image_strategy_module: "parsers.CJ3.cj3_strategies"
    link_strategy_class: "CJ3LinkHandlingStrategy"
    image_strategy_class: "CJ3ImageHandlingStrategy"
    tag_map_path: "resources/CJ3/mapping/tag_map.json"
    appendix_entries_path: "resources/CJ3/mapping/appendix_entries.json"
    has_appendix: True
    has_audio: True
    use_jmdict: False
    ignored_elements: {"entry-index"}
  
  kjt:
    dict_name: "旺文社漢字典 第四版"
    rev_name: "kjt"
    dict_type: "KJT"
    parser_module: "parsers.KJT.kjt_parser"
    parser_class_name: "KJTParser"
    link_strategy_module: "parsers.KJT.kjt_strategies"
    parse_all_links: True
    image_strategy_module: "parsers.KJT.kjt_strategies"
    link_strategy_class: "KJTLinkHandlingStrategy"
    image_strategy_class: "KJTImageHandlingStrategy"
    tag_map_path: "src/parsers/KJT/mapping/tag_map.json"
    image_map_path: "src/parsers/KJT/mapping/image_file_map.json"
    appendix_entries_path: "src/parsers/KJT/mapping/appendix_entries.json"
    has_appendix: True
    use_jmdict: False
    ignored_elements: {"entry-index"}
    expression_element: "subitem"

  RGKA9:
    dict_name: "例解学習漢字辞典 第九版"
    rev_name: "rgka9"
    dict_type: "RGKA9"
    parser_module: "parsers.Monokakido.parser"
    parser_class_name: "MonokakidoParser"
    tag_map_path: "resources/RGKA9/mapping/tag_mapping.json"
    appendix_entries_path: "resources/RGKA9/mapping/appendix_entries.json"
    has_appendix: False
    use_jmdict: False
    ignored_elements: {"entry-index"}
    expression_element: {"subitem"}

  NDS:
    dict_name: "精選版 日本国語大辞典"
    rev_name: "nds"
    dict_type: "NDS"
    parser_module: "parsers.NDS.nds_parser"
    parser_class_name: "NDSParser"
    link_strategy_module: "parsers.NDS.nds_strategies"
    link_strategy_class: "NDSLinkHandlingStrategy"
    image_strategy_module: "strategies.image"
    image_strategy_class: "HashedImageStrategy"
    pos_tag_strategy_class: "NDSPosTagStrategy"
    tag_map_path: "data/NDS/mapping/tag_mapping.json"
    image_map_path: "data/NDS/mapping/image_map.json"
    has_appendix: False
    use_jmdict: False
    ignored_elements: {"entry-index"}
    expression_element: {"子項目"}


  KNEJ:
    dict_name: "新英和大辞典 第6版"
    rev_name: "knej6"
    dict_type: "KNEJ"
    parser_module: "parsers.KNEJ"
    parser_class_name: "KNEJParser"
    tag_map_path: "resources/KNEJ/mapping/tag_map.json"
    use_index: False
    use_jmdict: False
    ignored_elements: { "entry-index", "key" }
    expression_element: "subitem"


  SOEJT:
    dict_name: "オックスフォード英語類語辞典"
    rev_name: "soejt"
    dict_type: "SOEJT"
    parser_module: "parsers.SOEJT"
    parser_class_name: "SOEJTParser"
    tag_map_path: "resources/SOEJT/mapping/tag_map.json"
    use_jmdict: False
    ignored_elements: {"entry-index"}


  LH7:
    dict_name: "ライトハウス英和辞典 第7版"
    rev_name: "lh7"
    dict_type: "LH7"
    parser_module: "parsers.LH7"
    parser_class_name: "LH7Parser"
    link_strategy_module: "strategies.plugins.LH7"
    link_strategy_class: "LH7LinkHandlingStrategy"
    tag_map_path: "resources/LH7/mapping/tag_map.json"
    use_jmdict: False
    ignored_elements: { "entry-index" }
    expression_element: "subitem"
