

dictionaries:
  daijisen: 
    dict_name: "大辞泉 第二版"
    rev_name: "daijisen2"
    dict_type: "Daijisen"
    parser_module: "parsers.DAIJISEN"
    parser_class_name: "DaijisenParser"
    link_strategy_module: "parsers.DAIJISEN.daijisen_strategies"
    image_strategy_module: "parsers.DAIJISEN.daijisen_strategies"
    link_strategy_class: "DaijisenLinkHandlingStrategy"
    image_strategy_class: "DaijisenImageHandlingStrategy"
    tag_map_path: "src/parsers/DAIJISEN/tag_map.json"
  
  kogo: 
    dict_name: "旺文社全訳古語辞典"
    rev_name: "oubunsha_kogo5"
    dict_type: "OZK5"
    parser_module: "parsers.OZK5"
    parser_class_name: "OZK5Parser"
    link_strategy_module: "parsers.OZK5.ozk5_strategies"
    link_strategy_class: "OZK5LinkHandlingStrategy"
    tag_map_path: "src/parsers/OZK5/tag_map.json"
    has_audio: True
  
  skogo: 
    dict_name: "三省堂全訳読解古語辞典"
    rev_name: "skogo5"
    dict_type: "SKOGO"
    parser_module: "parsers.SKOGO"
    parser_class_name: "SKOGOParser"
    link_strategy_module: "parsers.SKOGO.skogo_strategies"
    image_strategy_module: "parsers.SKOGO.skogo_strategies"
    link_strategy_class: "SKOGOLinkHandlingStrategy"
    image_strategy_class: "SKOGOImageHandlingStrategy"
    tag_map_path: "src/parsers/SKOGO/mapping/tag_map.json"
  
  ydp: 
    dict_name: "有斐閣現代心理学辞典"
    rev_name: "ydp1"
    dict_type: "YDP"
    parser_module: "parsers.YDP"
    parser_class_name: "YDPParser"
    image_strategy_module: "parsers.YDP.ydp_strategies"
    image_strategy_class: "YDPImageHandlingStrategy"
    tag_map_path: "src/parsers/YDP/tag_map.json"
  
  shinjigen: 
    dict_name: "角川新字源 改訂新版"
    rev_name: "shinjigen2"
    dict_type: "SHINJIGEN2"
    parser_module: "parsers.SHINJIGEN2"
    parser_class_name: "ShinjigenParser"
    image_strategy_module: "parsers.SHINJIGEN2.shinjigen2_strategies"
    image_strategy_class: "ShinjigenImageHandlingStrategy"
    tag_map_path: "src/parsers/SHINJIGEN2/tag_map.json"
    use_index: False
    use_jmdict: False
  
  nanmed: 
    dict_name: "南山堂医学大辞典 第20版"
    rev_name: "nanmed20"
    dict_type: "NANMED20"
    parser_module: "parsers.NANMED20"
    parser_class_name: "NanmedParser"
    image_strategy_module: "parsers.NANMED20.nanmed_strategies"
    image_strategy_class: "NanmedImageHandlingStrategy"
    tag_map_path: "src/parsers/NANMED20/tag_map.json"
    use_index: False
    use_jmdict: False
  
  meikyo: 
    dict_name: "明鏡国語辞典 第三版"
    rev_name: "meikyo3"
    dict_type: "MK3"
    parser_module: "parsers.MK3"
    parser_class_name: "MeikyoParser"
    link_strategy_module: "parsers.MK3.meikyo_strategies"
    link_strategy_class: "MeikyoLinkHandlingStrategy"
    tag_map_path: "src/parsers/MK3/tag_map.json"
  
  ydl: 
    dict_name: "有斐閣法律用語辞典 第5版"
    rev_name: "ydl"
    dict_type: "YDL"
    parser_module: "parsers.YDL"
    parser_class_name: "YDLParser"
    image_strategy_module: "parsers.OKO12.oko12_strategies"
    image_strategy_class: "Oko12ImageHandlingStrategy"
    tag_map_path: "src/parsers/YDL/tag_map.json"
  
  tismkanji: 
    dict_name: "TISMKANJI"
    rev_name: "kanjirin"
    dict_type: "TISMKANJI"
    parser_module: "parsers.TISMKANJI"
    parser_class_name: "TismKanjiParser"
    use_index: False
    use_jmdict: False
  
  oko12: 
    dict_name: "旺文社国語辞典 第十二版"
    rev_name: "oko12"
    dict_type: "OKO12"
    parser_module: "parsers.OKO12.oko12_parser"
    parser_class_name: "Oko12Parser"
    link_strategy_module: "parsers.OKO12.oko12_strategies"
    image_strategy_module: "parsers.OKO12.oko12_strategies"
    link_strategy_class: "Oko12LinkHandlingStrategy"
    image_strategy_class: "Oko12ImageHandlingStrategy"
    tag_map_path: "src/parsers/OKO12/tag_map.json"
  
  rgko12: 
    dict_name: "小学館例解学習国語 第十二版"
    rev_name: "rgko12"
    dict_type: "RGKO12"
    parser_module: "parsers.RGKO12.rgko12_parser"
    parser_class_name: "Rgko12Parser"
    link_strategy_module: "parsers.RGKO12.rgko12_strategies"
    image_strategy_module: "parsers.RGKO12.rgko12_strategies"
    link_strategy_class: "Rgko12LinkHandlingStrategy"
    image_strategy_class: "Rgko12ImageHandlingStrategy"
    tag_map_path: "src/parsers/RGKO12/mapping/tag_map.json"
    appendix_entries_path: "src/parsers/RGKO12/mapping/appendix_entries.json"
    has_appendix: True
    ignored_elements: {"entry-index", "hidden", "ht"}
  
  cj3: 
    dict_name: "小学館中日辞典 第3版"
    rev_name: "cj3"
    dict_type: "CJ3"
    parser_module: "parsers.CJ3.cj3_parser"
    parser_class_name: "CJ3Parser"
    link_strategy_module: "parsers.CJ3.cj3_strategies"
    image_strategy_module: "parsers.CJ3.cj3_strategies"
    link_strategy_class: "CJ3LinkHandlingStrategy"
    image_strategy_class: "CJ3ImageHandlingStrategy"
    tag_map_path: "src/parsers/CJ3/mapping/tag_map.json"
    appendix_entries_path: "src/parsers/CJ3/mapping/appendix_entries.json"
    has_appendix: True
    has_audio: True
    use_jmdict: False
  
  kjt:
    dict_name: "旺文社漢字典 第四第"
    rev_name: "kjt"
    dict_type: "KJT"
    parser_module: "parsers.KJT.kjt_parser"
    parser_class_name: "KJTParser"
    tag_map_path: "src/parsers/KJT/mapping/tag_map.json"
    appendix_entries_path: "src/parsers/KJT/mapping/appendix_entries.json"
    has_appendix: True
    use_jmdict: False